import {startMedia} from './media-monitor.js';
import {monitorIntegrity} from './integrity-monitor.js';

const $=id=>document.getElementById(id);
let interview=null,position=0,media=null,stopIntegrity=null,recognition=null,startedAt=0,transcript='',timer=null,demoMode=false;

const showApp=()=>{document.querySelector('.page-shell').hidden=true;$('app-shell').hidden=false;window.scrollTo({top:0,behavior:'instant'})};
const showLanding=()=>{document.querySelector('.page-shell').hidden=false;$('app-shell').hidden=true};
const showAuth=()=>{$('auth-overlay').hidden=false;setTimeout(()=>$('email').focus(),50)};
const hideAuth=()=>{$('auth-overlay').hidden=true};

async function api(path,options={}){const headers=options.body instanceof FormData?{}:{'Content-Type':'application/json',...(options.headers||{})};const r=await fetch('/api'+path,{credentials:'include',headers,...options});if(!r.ok){let message='Request failed';try{const data=await r.json();message=data.error||message}catch{}throw new Error(message)}return r.status===204?null:r.json()}
function initials(email){return(email||'AM').split('@')[0].slice(0,2).toUpperCase()}
function startTimer(){clearInterval(timer);startedAt=Date.now();timer=setInterval(()=>{const s=Math.floor((Date.now()-startedAt)/1000);$('answer-time').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},500)}
function stopTimer(){clearInterval(timer);$('answer-time').textContent='00:00'}
function metrics(){const seconds=Math.max(1,(Date.now()-startedAt)/1000),words=(transcript.match(/\b[\w'-]+\b/g)||[]).length,fillers=(transcript.match(/\b(um|uh|like|actually|basically)\b/gi)||[]).length;return{pace:Math.round(words/seconds*60),fillerCount:fillers,silenceSeconds:0,hesitationCount:fillers,confidence:Math.max(0,85-fillers*4),fluency:Math.max(0,90-fillers*5)}}
function renderQuestion(){const q=interview.questions[position];$('progress').textContent=`QUESTION ${position+1} / ${interview.questions.length}`;$('progress-fill').style.width=`${((position)/interview.questions.length)*100}%`;$('question-category').textContent=`QUESTION ${String(position+1).padStart(2,'0')} · ${(q.category||'INTERVIEW').toUpperCase()}`;$('question').textContent=q.prompt;$('timeline').innerHTML=interview.questions.map((x,i)=>`<li class="${i===position?'active':''}">${String(i+1).padStart(2,'0')} &nbsp; ${x.category}</li>`).join('');$('transcript').textContent='Your spoken answer will appear here.';$('feedback').hidden=true;transcript='';$('answer').textContent='Start answer';$('answer').disabled=false}
function startRecognition(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){$('setup-error').textContent='Speech recognition needs Chrome or Edge. Demo mode can still be used for the frontend preview.';demoMode=true;return startDemoAnswer()}recognition=new Speech();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';recognition.onresult=e=>{transcript=Array.from(e.results).map(r=>r[0].transcript).join(' ');$('transcript').textContent=transcript||'Listening…'};recognition.onerror=e=>{if(e.error!=='no-speech')$('transcript').textContent='Microphone input paused. Try again.'};recognition.start();startTimer();$('answer').textContent='Finish and evaluate'}
function startDemoAnswer(){transcript='I would first clarify the impact, reproduce the issue, inspect the metrics and logs, then test the smallest safe change. I would measure the result and document the trade-off.';$('transcript').textContent=transcript;startTimer();setTimeout(()=>$('answer').textContent='Finish and evaluate',300)}
async function evaluate(){recognition?.stop();stopTimer();$('answer').disabled=true;try{let e;if(demoMode){e={overall:84,technical:88,hr:82,communication:86,grammar:91,vocabulary:84,confidence:80,feedback:'Strong structured answer. You explained a clear diagnostic process and showed good ownership. Add a measurable result to make the answer more convincing.',followUp:'What metric would you use to prove that your fix improved the system?',strengths:['Clear troubleshooting flow','Good ownership','Relevant technical reasoning'],weaknesses:['No measurable outcome'],suggestions:['Lead with impact','Add a metric','Keep the answer concise']}}else{e=await api(`/interviews/${interview.id}/answers`,{method:'POST',body:JSON.stringify({position,transcript,voiceMetrics:metrics()})})}$('overall').textContent=`Overall score: ${e.overall}/100`;$('score-badge').textContent=e.overall;$('scores').innerHTML=[['Technical',e.technical],['Communication',e.communication],['Confidence',e.confidence],['Grammar',e.grammar]].map(([n,v])=>`<div>${n}<b>${v}</b></div>`).join('');$('feedback-text').textContent=e.feedback;$('follow-up').textContent=e.followUp;$('feedback').hidden=false;$('answer').disabled=false;$('answer').textContent='Answer recorded'}catch(err){$('transcript').textContent=err.message;$('answer').disabled=false}}
async function beginInterview(form){const data=new FormData(form);$('setup-error').textContent='';$('start-form button[type=submit]').disabled=true;try{let result;try{result=await api('/interviews',{method:'POST',body:data})}catch(err){demoMode=true;result={id:'demo',questions:[{category:'Technical',prompt:'Tell me about a technical problem you solved recently.',rubric:''},{category:'Project',prompt:'Walk me through a project you are proud of.',rubric:''},{category:'Problem Solving',prompt:'Describe a difficult issue and how you approached it.',rubric:''},{category:'Cloud',prompt:'How would you design a reliable cloud workload?',rubric:''},{category:'Behavioral',prompt:'Tell me about a time you learned from a mistake.',rubric:''},{category:'Leadership',prompt:'How do you communicate technical trade-offs to others?',rubric:''}]};$('setup-error').textContent='Demo mode is active because the backend is not connected. Add your .env and database to use live AI scoring.'}interview=result;position=0;showView('room');$('interview-title').textContent=`${data.get('role')||'Technical'} · ${data.get('level')||'mid'}-level`;renderQuestion();if(!demoMode){try{media=await startMedia($('camera'),event=>api(`/interviews/${interview.id}/integrity-events`,{method:'POST',body:JSON.stringify(event)}).catch(()=>{}),state=>{$('mic-status').textContent=`Microphone: ${state.mic?'active':'muted'}`;$('camera-status').textContent=`Camera: ${state.camera?'active':'disabled'}`;$('media-fallback').style.display=state.camera?'none':'grid'})}catch{$('mic-status').textContent='Microphone: unavailable';$('camera-status').textContent='Camera: unavailable'}stopIntegrity=monitorIntegrity(event=>api(`/interviews/${interview.id}/integrity-events`,{method:'POST',body:JSON.stringify(event)}).catch(()=>{}))}}catch(err){$('setup-error').textContent=err.message}finally{$('start-form button[type=submit]').disabled=false}}
function showView(view){document.querySelectorAll('.app-view').forEach(x=>x.hidden=true);$(`${view}-view`).hidden=false;document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
async function loadHistory(){try{const rows=await api('/interviews');$('history-list').innerHTML=rows.length?rows.map(x=>{const p=typeof x.profile==='string'?JSON.parse(x.profile):x.profile;return `<div class="history-row"><strong>${p.role||'Interview'} · ${p.level||''}</strong><span>${new Date(x.created_at).toLocaleDateString()}</span><span class="score-mini">${x.overall_score??'—'}/100</span><span>${x.status}</span></div>`}).join(''):'<div class="empty-history">No sessions yet. Start your first practice interview.</div>'}catch{$('history-list').innerHTML='<div class="empty-history">Connect the backend to load saved sessions.</div>'}}

$('header-start').onclick=showAuth;$('hero-start').onclick=showAuth;$('results-start').onclick=showAuth;$('close-auth').onclick=hideAuth;$('auth-backdrop').onclick=hideAuth;
$('auth-form').onsubmit=async e=>{e.preventDefault();await authenticate(false)};$('register').onclick=()=>authenticate(true);$('demo-login').onclick=()=>{demoMode=true;hideAuth();showApp();$('user-avatar').textContent='DE';showView('setup')};
async function authenticate(create){$('auth-error').textContent='';try{await api(`/auth/${create?'register':'login'}`,{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});$('user-avatar').textContent=initials($('email').value);hideAuth();showApp();showView('setup')}catch(err){$('auth-error').textContent=err.message}}
$('start-form').onsubmit=e=>{e.preventDefault();beginInterview(e.target)};$('listen').onclick=()=>{const q=interview?.questions?.[position];if(q)speechSynthesis.speak(new SpeechSynthesisUtterance(q.prompt))};$('answer').onclick=()=>recognition||demoMode?evaluate():startRecognition();
$('next').onclick=()=>{position++;recognition=null;if(position<interview.questions.length){renderQuestion()}else{media?.stop();stopIntegrity?.();showView('finish');$('report').href=demoMode?'#':`/api/interviews/${interview.id}/report.pdf`}};
$('new-session').onclick=()=>{demoMode=false;showView('setup');$('start-form').reset()};$('history-button').onclick=()=>{showView('history');loadHistory()};$('logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}catch{}showLanding()};
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>{if(b.dataset.view==='history'){showView('history');loadHistory()}else showView('setup')});
if(new URLSearchParams(location.search).has('demo')){demoMode=true;showApp();showView('setup')}
